version: "3"
services:
  server:
    build: .
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./app:/go/app

  mysql:
    image: mysql:5.7
    container_name: "mysql-container"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: todo
      MYSQL_USER: todo
      MYSQL_PASSWORD: todo
      MYSQL_DATABASE: todo
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"

  # phpMyAdmin
  phpmyadmin:
    container_name: php_my_admin
    image: phpmyadmin/phpmyadmin
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOSTS=mysql-container
    - PMA_USER=root
    - PMA_PASSWORD=todo
    ports:
      - 8080:80
