
USE todo;

CREATE TABLE `users`(
  id          BIGINT(20)   NOT NULL AUTO_INCREMENT,
  name        VARCHAR(20)  NOT NULL,
  email       VARCHAR(50)  NOT NULL,
  password    VARCHAR(255) NOT NULL,
  created_at  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE tickets(
  id          BIGINT(20)   NOT NULL AUTO_INCREMENT,
  epic_id     BIGINT(20)   NOT NULL,
  title       VARCHAR(40)  NOT NULL,
  description VARCHAR(255) DEFAULT NULL,
  status      tinyint      DEFAULT NULL,
  created_at  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE epics(
  id          BIGINT(20)  NOT NULL AUTO_INCREMENT,
  title       VARCHAR(25) NOT NULL,
  color       tinyint     NOT NULL,
  created_at  DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

